[package]
name = "rtic_control_testing"
version = "0.1.0"
authors = ["Dylan Cullinane <dcullina@ucsd.edu>"]
edition = "2021"

[dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
defmt = "0.3.8"
# rtic = { version = "2.0.0", features = [ "thumbv7-backend" ] }
cortex-m-rt = "0.7"
panic-probe = { version = "0.3.1", features = ["defmt"] }
cortex-m-rtic = "1.1"
defmt-rtt = "0.4.1"

[dependencies.stm32f4xx-hal]
version = "0.20.0"
features = ["stm32f411", "rtic2", "defmt"]

# Set the default for dependencies.
[profile.dev.package."*"]
opt-level = "s"

[profile.release]
codegen-units = 1
incremental = false
debug = true
lto = true
opt-level = "s"
